### ISSUE TITLE
Generate Synthetic Data

### ISSUE THREAD

**Issue by aleximmer** [GlooperLabs/GraphTime#9]
To run simulation for synthetic data it would be good to vary it slightly with different random seeds. This would help for the performance evaluation, too. In fact, we could generate data and measure how well the structure can be restored wrt l1 and l2.

**Comment by AlexGibberd** [comment]
It is a good idea to generate many simulated data-streams from a single known graph structure, then we can see how well it recovers the graph for that particular example of graph structure.

It's quite hard to empirically verify performance over many graph structures, as one would have to run the whole parameter (lambda) sweep routine for each drawn example of data. For example we have to consider Nlambda x Ndraws x Ngraphs estimates. I actually considered this kind of set up in my paper, where I attempted to see how performance scaled vs the number of nodes (p), and the number of data-points (T) but it is only really feasible for very small problem sizes.

Either way, it is good to have a couple of functions for both simulating ground-truth precision matrices (effectively the true graphs), and then generating data from these true underlying models.
